//! # D-Bus interface proxy for: `org.shadowblip.Input.Source.EventDevice`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `org.shadowblip.Input.Source.EventDevice.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::PeerProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "org.shadowblip.Input.Source.EventDevice",
    assume_defaults = true
)]
pub trait EventDevice {
    /// DevicePath property
    #[zbus(property)]
    fn device_path(&self) -> zbus::Result<String>;

    /// Handlers property
    #[zbus(property)]
    fn handlers(&self) -> zbus::Result<Vec<String>>;

    /// Name property
    #[zbus(property)]
    fn name(&self) -> zbus::Result<String>;

    /// PhysPath property
    #[zbus(property)]
    fn phys_path(&self) -> zbus::Result<String>;

    /// SysfsPath property
    #[zbus(property)]
    fn sysfs_path(&self) -> zbus::Result<String>;

    /// UniqueId property
    #[zbus(property)]
    fn unique_id(&self) -> zbus::Result<String>;
}
